service:
  name: cloud-dev-capstone

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

functions:
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  hello:
    handler: src/lambda/http/handler.handler
    events:
      - http:
          method: get
          path: hello
          cors: true
          authorizer: Auth
